function [fitresult, gof] = createPolyFit(xData, prices)
%CREATEFIT(XDATA,PRICES)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xData
%      Y Output: prices
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Dec-2015 14:10:39


%% Fit: 'untitled fit 1'.
[xData_1, yData] = prepareCurveData( xData, prices );

% Set up fittype and options.
ft = fittype( 'poly9' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData_1, yData, ft, opts );
