
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                          INPUT                                 %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Load the common settings.
init_common_settings_3;
close all;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                          SOLVER                                %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plot_option = 0;
nz = 0;
pd = 'normal';

predErrStd=0.0;
% N_samples = 5;
if predErrStd==0 
    N_samples = 1;
end
progressbar;

for iter=1:N_samples
    addPredictionErrors;

    %% supply only
    [cost_supply,capacity_supply,emission_supply] = ...
        houston_grid_longterm(0,nz,0,0, ...
        T, N_y, ...
        IP,PP,OP,IT,CO2_grid,a_Array ...
        ,au, ...
        con, BS_Array ...
        ,A_Array, ...
        S,E,bu,PUE_low,R(1,:), ...
        RR,RC_Array ...
        ,RE,SR, ...
        CRR, ...
        CRC_Array ...
        ,CRE,P, GP_Array ...
        ,RP,BP,plot_option,[fig_path 'nz-supply_year']);
    % realize supply only
    [cost_supply_actual, emission_supply_actual] = ...
        realize_houston_grid_longterm(0,nz,0,0, ...
        T, N_y, ...
        IP,PP,OP,IT,CO2_grid,a_Array_real ...
        ,au, ...
        con, BS_Array_real ...
        ,A_Array, ...
        S,E,bu,PUE_low,R_real(1,:), ...
        RR,RC_Array ...
        ,RE,SR, ...
        CRR, ...
        CRC_Array_real ...
        ,CRE,P, GP_Array_real ...
        ,RP,BP,capacity_supply);
     
    %% integrated
    [cost_int, capacity_int, emission_int] = houston_grid_longterm(1,nz,1,1, ...
        T, N_y, ...
        IP, PP, OP, IT, CO2_grid, a_Array ...
        ,au, ...
        con, BS_Array ...
        ,A_Array, ...
        S,E,bu,PUE_low,R(1,:), ...
        RR,RC_Array ...
        ,RE,SR, ...
        CRR, ...
        CRC_Array ...
        ,CRE,P, GP_Array ...
        ,RP,BP,plot_option,[fig_path 'nz-int_year']);
    % realize the installed capacity & optimize the demand
    [cost_int_actual,emission_int_actual] = realize_houston_grid_longterm(1,nz,1,1, ...
        T, N_y, ...
        IP,PP,OP,IT,CO2_grid,a_Array_real ...
        ,au, ...
        con, BS_Array_real ...
        ,A_Array, ...
        S,E,bu,PUE_low,R_real(1,:), ...
        RR,RC_Array ...
        ,RE,SR, ...
        CRR, ...
        CRC_Array_real ...
        ,CRE,P, GP_Array_real ...
        ,RP,BP,capacity_int);
    % average.
    if iter == 1
        cost_supply_mean = cost_supply;
        capacity_supply_mean = capacity_supply;
        emission_supply_mean = emission_supply;
        
        cost_supply_mean_actual = cost_supply_actual;
        emission_supply_mean_actual = emission_supply_actual;

        cost_int_mean = cost_int;
        capacity_int_mean = capacity_int;
        emission_int_mean = emission_int;
        
        cost_int_mean_actual = cost_int_actual;
        emission_int_mean_actual = emission_int_actual;
    else
        cost_supply_mean = cost_supply_mean + cost_supply;
        capacity_supply_mean = capacity_supply_mean + capacity_supply;
        emission_supply_mean = emission_supply_mean + emission_supply;
        
        cost_supply_mean_actual = cost_supply_mean_actual + cost_supply_actual;
        emission_supply_mean_actual = emission_supply_mean_actual + emission_supply_actual;
        
        cost_int_mean = cost_int_mean + cost_int;
        capacity_int_mean = capacity_int_mean + capacity_int;
        emission_int_mean = emission_int_mean + emission_int;
        
        cost_int_mean_actual = cost_int_mean_actual+ cost_int_actual;
        emission_int_mean_actual = emission_int_mean_actual + emission_int_actual;
    end
    progressbar(iter/N_samples);
end
%%
cost_supply_mean     = cost_supply_mean/N_samples;
capacity_supply_mean = capacity_supply_mean/N_samples;
emission_supply_mean = emission_supply_mean/N_samples;

cost_supply_mean_actual     = cost_supply_mean_actual/N_samples;
emission_supply_mean_actual = emission_supply_mean_actual/N_samples;

cost_int_mean     = cost_int_mean/N_samples;
capacity_int_mean = capacity_int_mean/N_samples;
emission_int_mean = emission_int_mean/N_samples;

cost_int_mean_actual     = cost_int_mean_actual/N_samples;
emission_int_mean_actual = emission_int_mean_actual/N_samples;

sum(sum(cost_supply_mean_actual))

sum(sum(cost_int_mean_actual))

sum(sum(emission_int_mean_actual))

fileName = strcat('results/TCO_comparison_err_',num2str(predErrStd),'.mat');
save(fileName);